import { University } from '@/types';

export const UNIVERSITIES: University[] = [
  {
    id: 'harvard',
    name: 'Harvard University',
    link: 'https://www.harvard.edu',
    logoSeed: 'harvard',
    avgRating: 4.5,
    reviewCount: 10,
    admission: {
      requirements: 'Requires SAT/ACT, 3.8+ GPA, 2 recommendation letters',
      deadline: 'Jan 1',
      documents: ['Transcripts', 'Recommendation Letters', 'Personal Statement'],
    },
    visa: {
      type: 'F-1',
      steps: [
        'Complete DS-160 form',
        'Pay SEVIS fee ($350)',
        'Schedule and attend visa interview',
      ],
      fee: '$350',
    },
    scholarships: [
      {
        name: 'Fulbright Scholarship',
        description: 'Full tuition for international students',
        eligibility: 'Academic excellence, leadership',
        link: 'https://foreign.fulbrightonline.org/',
      },
      {
        name: 'Harvard Financial Aid',
        description: 'Need-based aid for all admitted students',
        eligibility: 'Demonstrated financial need',
        link: 'https://college.harvard.edu/financial-aid',
      },
      {
        name: 'Boustany Foundation Scholarship',
        description: 'MBA scholarship for international students',
        eligibility: 'MBA applicants, strong academic record',
        link: 'https://www.boustany-foundation.org/scholarship-programs/mba-harvard/',
      },
    ],
  },
  {
    id: 'mit',
    name: 'Massachusetts Institute of Technology (MIT)',
    link: 'https://web.mit.edu/',
    logoSeed: 'mit',
    avgRating: 4.7,
    reviewCount: 12,
    admission: {
      requirements: 'Requires SAT/ACT, strong STEM background, essays',
      deadline: 'Jan 1',
      documents: ['Transcripts', 'Recommendation Letters', 'Essays'],
    },
    visa: {
      type: 'F-1',
      steps: [
        'Complete DS-160 form',
        'Pay SEVIS fee ($350)',
        'Schedule and attend visa interview',
      ],
      fee: '$350',
    },
    scholarships: [
      {
        name: 'MIT Scholarships',
        description: 'Need-based scholarships for undergraduates',
        eligibility: 'Demonstrated financial need',
        link: 'https://sfs.mit.edu/undergraduate-students/financial-aid/mit-scholarships/',
      },
      {
        name: 'Fulbright Scholarship',
        description: 'Full tuition for international students',
        eligibility: 'Academic excellence, leadership',
        link: 'https://foreign.fulbrightonline.org/',
      },
      {
        name: 'Legatum Fellowship',
        description: 'Entrepreneurship scholarship for MIT students',
        eligibility: 'Entrepreneurial focus',
        link: 'https://legatum.mit.edu/fellowship/',
      },
    ],
  },
  {
    id: 'stanford',
    name: 'Stanford University',
    link: 'https://www.stanford.edu/',
    logoSeed: 'stanford',
    avgRating: 4.6,
    reviewCount: 9,
    admission: {
      requirements: 'Requires SAT/ACT, essays, 2 recommendation letters',
      deadline: 'Jan 2',
      documents: ['Transcripts', 'Recommendation Letters', 'Essays'],
    },
    visa: {
      type: 'F-1',
      steps: [
        'Complete DS-160 form',
        'Pay SEVIS fee ($350)',
        'Schedule and attend visa interview',
      ],
      fee: '$350',
    },
    scholarships: [
      {
        name: 'Knight-Hennessy Scholars',
        description: 'Full funding for graduate study at Stanford',
        eligibility: 'Graduate applicants, leadership',
        link: 'https://knight-hennessy.stanford.edu/',
      },
      {
        name: 'Stanford GSB Fellowships',
        description: 'Fellowships for MBA students',
        eligibility: 'MBA applicants',
        link: 'https://www.gsb.stanford.edu/programs/mba/financial-aid/fellowships',
      },
      {
        name: 'Fulbright Scholarship',
        description: 'Full tuition for international students',
        eligibility: 'Academic excellence, leadership',
        link: 'https://foreign.fulbrightonline.org/',
      },
    ],
  },
  {
    id: 'oxford',
    name: 'University of Oxford',
    link: 'https://www.ox.ac.uk/',
    logoSeed: 'oxford',
    avgRating: 4.4,
    reviewCount: 8,
    admission: {
      requirements: 'A-levels or equivalent, admissions test, interview',
      deadline: 'Oct 15',
      documents: ['Transcripts', 'Recommendation Letters', 'Admissions Test'],
    },
    visa: {
      type: 'Student Visa (UK)',
      steps: [
        'Apply for CAS from Oxford',
        'Complete UK visa application',
        'Schedule and attend visa interview',
      ],
      fee: '£348',
    },
    scholarships: [
      {
        name: 'Rhodes Scholarship',
        description: 'Full funding for international students',
        eligibility: 'Exceptional academic achievement',
        link: 'https://www.rhodeshouse.ox.ac.uk/scholarships/',
      },
      {
        name: 'Clarendon Fund',
        description: 'Graduate scholarships for all nationalities',
        eligibility: 'Graduate applicants',
        link: 'https://www.ox.ac.uk/clarendon',
      },
      {
        name: 'Chevening Scholarship',
        description: 'UK government scholarship for international students',
        eligibility: 'Leadership, academic merit',
        link: 'https://www.chevening.org/',
      },
    ],
  },
  {
    id: 'cambridge',
    name: 'University of Cambridge',
    link: 'https://www.cam.ac.uk/',
    logoSeed: 'cambridge',
    avgRating: 4.3,
    reviewCount: 7,
    admission: {
      requirements: 'A-levels or equivalent, admissions test, interview',
      deadline: 'Oct 15',
      documents: ['Transcripts', 'Recommendation Letters', 'Admissions Test'],
    },
    visa: {
      type: 'Student Visa (UK)',
      steps: [
        'Apply for CAS from Cambridge',
        'Complete UK visa application',
        'Schedule and attend visa interview',
      ],
      fee: '£348',
    },
    scholarships: [
      {
        name: 'Gates Cambridge Scholarship',
        description: 'Full-cost scholarships for graduate study',
        eligibility: 'Graduate applicants, academic excellence',
        link: 'https://www.gatescambridge.org/',
      },
      {
        name: 'Cambridge International Scholarships',
        description: 'For international PhD students',
        eligibility: 'PhD applicants',
        link: 'https://www.cambridgetrust.org/scholarships/',
      },
      {
        name: 'Chevening Scholarship',
        description: 'UK government scholarship for international students',
        eligibility: 'Leadership, academic merit',
        link: 'https://www.chevening.org/',
      },
    ],
  },
  {
    id: 'caltech',
    name: 'California Institute of Technology (Caltech)',
    link: 'https://www.caltech.edu/',
    logoSeed: 'caltech',
    avgRating: 4.7,
    reviewCount: 6,
    admission: {
      requirements: 'Requires SAT/ACT, strong STEM background, essays',
      deadline: 'Jan 3',
      documents: ['Transcripts', 'Recommendation Letters', 'Essays'],
    },
    visa: {
      type: 'F-1',
      steps: [
        'Complete DS-160 form',
        'Pay SEVIS fee ($350)',
        'Schedule and attend visa interview',
      ],
      fee: '$350',
    },
    scholarships: [
      {
        name: 'Caltech Scholarships',
        description: 'Need-based scholarships for undergraduates',
        eligibility: 'Demonstrated financial need',
        link: 'https://finaid.caltech.edu/typesofaid/caltechscholarships',
      },
      {
        name: 'Fulbright Scholarship',
        description: 'Full tuition for international students',
        eligibility: 'Academic excellence, leadership',
        link: 'https://foreign.fulbrightonline.org/',
      },
    ],
  },
  {
    id: 'princeton',
    name: 'Princeton University',
    link: 'https://www.princeton.edu/',
    logoSeed: 'princeton',
    avgRating: 4.5,
    reviewCount: 8,
    admission: {
      requirements: 'Requires SAT/ACT, essays, 2 recommendation letters',
      deadline: 'Jan 1',
      documents: ['Transcripts', 'Recommendation Letters', 'Essays'],
    },
    visa: {
      type: 'F-1',
      steps: [
        'Complete DS-160 form',
        'Pay SEVIS fee ($350)',
        'Schedule and attend visa interview',
      ],
      fee: '$350',
    },
    scholarships: [
      {
        name: 'Princeton Financial Aid',
        description: 'Need-based aid for all admitted students',
        eligibility: 'Demonstrated financial need',
        link: 'https://admission.princeton.edu/cost-aid',
      },
      {
        name: 'Fulbright Scholarship',
        description: 'Full tuition for international students',
        eligibility: 'Academic excellence, leadership',
        link: 'https://foreign.fulbrightonline.org/',
      },
    ],
  },
  {
    id: 'yale',
    name: 'Yale University',
    link: 'https://www.yale.edu/',
    logoSeed: 'yale',
    avgRating: 4.4,
    reviewCount: 7,
    admission: {
      requirements: 'Requires SAT/ACT, essays, 2 recommendation letters',
      deadline: 'Jan 2',
      documents: ['Transcripts', 'Recommendation Letters', 'Essays'],
    },
    visa: {
      type: 'F-1',
      steps: [
        'Complete DS-160 form',
        'Pay SEVIS fee ($350)',
        'Schedule and attend visa interview',
      ],
      fee: '$350',
    },
    scholarships: [
      {
        name: 'Yale Scholarships',
        description: 'Need-based scholarships for undergraduates',
        eligibility: 'Demonstrated financial need',
        link: 'https://finaid.yale.edu/',
      },
      {
        name: 'Fulbright Scholarship',
        description: 'Full tuition for international students',
        eligibility: 'Academic excellence, leadership',
        link: 'https://foreign.fulbrightonline.org/',
      },
    ],
  },
  {
    id: 'uchicago',
    name: 'University of Chicago',
    link: 'https://www.uchicago.edu/',
    logoSeed: 'uchicago',
    avgRating: 4.3,
    reviewCount: 6,
    admission: {
      requirements: 'Requires SAT/ACT, essays, 2 recommendation letters',
      deadline: 'Jan 2',
      documents: ['Transcripts', 'Recommendation Letters', 'Essays'],
    },
    visa: {
      type: 'F-1',
      steps: [
        'Complete DS-160 form',
        'Pay SEVIS fee ($350)',
        'Schedule and attend visa interview',
      ],
      fee: '$350',
    },
    scholarships: [
      {
        name: 'UChicago Scholarships',
        description: 'Merit and need-based scholarships',
        eligibility: 'Academic merit or financial need',
        link: 'https://college.uchicago.edu/admissions/cost-aid',
      },
      {
        name: 'Fulbright Scholarship',
        description: 'Full tuition for international students',
        eligibility: 'Academic excellence, leadership',
        link: 'https://foreign.fulbrightonline.org/',
      },
    ],
  },
  {
    id: 'columbia',
    name: 'Columbia University',
    link: 'https://www.columbia.edu/',
    logoSeed: 'columbia',
    avgRating: 4.2,
    reviewCount: 7,
    admission: {
      requirements: 'Requires SAT/ACT, essays, 2 recommendation letters',
      deadline: 'Jan 1',
      documents: ['Transcripts', 'Recommendation Letters', 'Essays'],
    },
    visa: {
      type: 'F-1',
      steps: [
        'Complete DS-160 form',
        'Pay SEVIS fee ($350)',
        'Schedule and attend visa interview',
      ],
      fee: '$350',
    },
    scholarships: [
      {
        name: 'Columbia Financial Aid',
        description: 'Need-based aid for all admitted students',
        eligibility: 'Demonstrated financial need',
        link: 'https://cc-seas.financialaid.columbia.edu/',
      },
      {
        name: 'Fulbright Scholarship',
        description: 'Full tuition for international students',
        eligibility: 'Academic excellence, leadership',
        link: 'https://foreign.fulbrightonline.org/',
      },
    ],
  },
  {
    id: 'ucla',
    name: 'University of California, Los Angeles (UCLA)',
    link: 'https://www.ucla.edu/',
    logoSeed: 'ucla',
    avgRating: 4.3,
    reviewCount: 8,
    admission: {
      requirements: 'Requires SAT/ACT, essays, 2 recommendation letters',
      deadline: 'Nov 30',
      documents: ['Transcripts', 'Recommendation Letters', 'Essays'],
    },
    visa: {
      type: 'F-1',
      steps: [
        'Complete DS-160 form',
        'Pay SEVIS fee ($350)',
        'Schedule and attend visa interview',
      ],
      fee: '$350',
    },
    scholarships: [
      {
        name: 'UCLA Scholarships',
        description: 'Merit and need-based scholarships',
        eligibility: 'Academic merit or financial need',
        link: 'https://www.ucla.edu/admission/affordability',
      },
      {
        name: 'Fulbright Scholarship',
        description: 'Full tuition for international students',
        eligibility: 'Academic excellence, leadership',
        link: 'https://foreign.fulbrightonline.org/',
      },
    ],
  },
  {
    id: 'berkeley',
    name: 'University of California, Berkeley',
    link: 'https://www.berkeley.edu/',
    logoSeed: 'berkeley',
    avgRating: 4.4,
    reviewCount: 9,
    admission: {
      requirements: 'Requires SAT/ACT, essays, 2 recommendation letters',
      deadline: 'Nov 30',
      documents: ['Transcripts', 'Recommendation Letters', 'Essays'],
    },
    visa: {
      type: 'F-1',
      steps: [
        'Complete DS-160 form',
        'Pay SEVIS fee ($350)',
        'Schedule and attend visa interview',
      ],
      fee: '$350',
    },
    scholarships: [
      {
        name: 'Berkeley International Office Scholarships',
        description: 'Scholarships for international students',
        eligibility: 'International students',
        link: 'https://internationaloffice.berkeley.edu/students/new/scholarships',
      },
      {
        name: 'Fulbright Scholarship',
        description: 'Full tuition for international students',
        eligibility: 'Academic excellence, leadership',
        link: 'https://foreign.fulbrightonline.org/',
      },
    ],
  },
  {
    id: 'imperial',
    name: 'Imperial College London',
    link: 'https://www.imperial.ac.uk/',
    logoSeed: 'imperial',
    avgRating: 4.2,
    reviewCount: 7,
    admission: {
      requirements: 'A-levels or equivalent, admissions test, interview',
      deadline: 'Oct 15',
      documents: ['Transcripts', 'Recommendation Letters', 'Admissions Test'],
    },
    visa: {
      type: 'Student Visa (UK)',
      steps: [
        'Apply for CAS from Imperial',
        'Complete UK visa application',
        'Schedule and attend visa interview',
      ],
      fee: '£348',
    },
    scholarships: [
      {
        name: 'Imperial College Scholarships',
        description: 'Scholarships for international students',
        eligibility: 'International students',
        link: 'https://www.imperial.ac.uk/study/ug/fees-and-funding/scholarships/',
      },
      {
        name: 'Chevening Scholarship',
        description: 'UK government scholarship for international students',
        eligibility: 'Leadership, academic merit',
        link: 'https://www.chevening.org/',
      },
    ],
  },
  {
    id: 'toronto',
    name: 'University of Toronto',
    link: 'https://www.utoronto.ca/',
    logoSeed: 'toronto',
    avgRating: 4.3,
    reviewCount: 8,
    admission: {
      requirements: 'Requires high school diploma, English proficiency',
      deadline: 'Jan 13',
      documents: ['Transcripts', 'Recommendation Letters', 'Essays'],
    },
    visa: {
      type: 'Study Permit (Canada)',
      steps: [
        'Apply for admission',
        'Receive Letter of Acceptance',
        'Apply for study permit',
      ],
      fee: 'CA$150',
    },
    scholarships: [
      {
        name: 'Lester B. Pearson International Scholarship',
        description: 'Full funding for international undergraduates',
        eligibility: 'International students, academic excellence',
        link: 'https://future.utoronto.ca/pearson/about/',
      },
      {
        name: 'U of T Scholarships',
        description: 'Various merit-based scholarships',
        eligibility: 'Academic merit',
        link: 'https://future.utoronto.ca/finances/scholarships/',
      },
    ],
  },
  {
    id: 'melbourne',
    name: 'University of Melbourne',
    link: 'https://www.unimelb.edu.au/',
    logoSeed: 'melbourne',
    avgRating: 4.2,
    reviewCount: 7,
    admission: {
      requirements: 'Requires high school diploma, English proficiency',
      deadline: 'Dec 31',
      documents: ['Transcripts', 'Recommendation Letters', 'Essays'],
    },
    visa: {
      type: 'Student Visa (Australia)',
      steps: [
        'Apply for admission',
        'Receive Letter of Offer',
        'Apply for student visa',
      ],
      fee: 'AU$650',
    },
    scholarships: [
      {
        name: 'Melbourne International Undergraduate Scholarship',
        description: 'Partial tuition for international students',
        eligibility: 'International students, academic excellence',
        link: 'https://scholarships.unimelb.edu.au/awards/melbourne-international-undergraduate-scholarship',
      },
      {
        name: 'Australia Awards Scholarships',
        description: 'Full funding for international students',
        eligibility: 'International students from eligible countries',
        link: 'https://www.dfat.gov.au/people-to-people/australia-awards',
      },
    ],
  },
  {
    id: 'tokyo',
    name: 'University of Tokyo',
    link: 'https://www.u-tokyo.ac.jp/en/',
    logoSeed: 'tokyo',
    avgRating: 4.1,
    reviewCount: 6,
    admission: {
      requirements: 'Requires high school diploma, English proficiency',
      deadline: 'Jan 15',
      documents: ['Transcripts', 'Recommendation Letters', 'Essays'],
    },
    visa: {
      type: 'Student Visa (Japan)',
      steps: [
        'Apply for admission',
        'Receive Certificate of Eligibility',
        'Apply for student visa',
      ],
      fee: '¥3,000',
    },
    scholarships: [
      {
        name: 'MEXT Scholarship',
        description: 'Full funding for international students',
        eligibility: 'International students, academic excellence',
        link: 'https://www.studyinjapan.go.jp/en/smap-stopj-applications-scholarships/',
      },
      {
        name: 'University of Tokyo Fellowships',
        description: 'Various fellowships for international students',
        eligibility: 'International students',
        link: 'https://www.u-tokyo.ac.jp/en/prospective-students/scholarships.html',
      },
    ],
  },
  {
    id: 'singapore',
    name: 'National University of Singapore (NUS)',
    link: 'https://www.nus.edu.sg/',
    logoSeed: 'nus',
    avgRating: 4.3,
    reviewCount: 8,
    admission: {
      requirements: 'Requires high school diploma, English proficiency',
      deadline: 'Mar 31',
      documents: ['Transcripts', 'Recommendation Letters', 'Essays'],
    },
    visa: {
      type: 'Student Pass (Singapore)',
      steps: [
        'Apply for admission',
        'Receive Letter of Offer',
        'Apply for student pass',
      ],
      fee: 'S$90',
    },
    scholarships: [
      {
        name: 'NUS Global Merit Scholarship',
        description: 'Full funding for international undergraduates',
        eligibility: 'International students, academic excellence',
        link: 'https://www.nus.edu.sg/oam/scholarships/freshmen/nus-global-merit-scholarship',
      },
      {
        name: 'ASEAN Undergraduate Scholarship',
        description: 'Partial tuition for ASEAN students',
        eligibility: 'ASEAN nationals',
        link: 'https://www.nus.edu.sg/oam/scholarships/freshmen/asean-undergraduate-scholarship',
      },
    ],
  },
  {
    id: 'munich',
    name: 'Technical University of Munich (TUM)',
    link: 'https://www.tum.de/en/',
    logoSeed: 'tum',
    avgRating: 4.1,
    reviewCount: 6,
    admission: {
      requirements: 'Requires high school diploma, English proficiency',
      deadline: 'Jul 15',
      documents: ['Transcripts', 'Recommendation Letters', 'Essays'],
    },
    visa: {
      type: 'Student Visa (Germany)',
      steps: [
        'Apply for admission',
        'Receive Letter of Admission',
        'Apply for student visa',
      ],
      fee: '€75',
    },
    scholarships: [
      {
        name: 'Deutschlandstipendium',
        description: 'Merit-based scholarship for students in Germany',
        eligibility: 'Academic merit',
        link: 'https://www.deutschlandstipendium.de/',
      },
      {
        name: 'TUM Scholarships',
        description: 'Various scholarships for international students',
        eligibility: 'International students',
        link: 'https://www.tum.de/en/studies/fees-and-financial-aid/scholarships/',
      },
    ],
  },
  {
    id: 'edinburgh',
    name: 'University of Edinburgh',
    link: 'https://www.ed.ac.uk/',
    logoSeed: 'edinburgh',
    avgRating: 4.2,
    reviewCount: 7,
    admission: {
      requirements: 'A-levels or equivalent, English proficiency',
      deadline: 'Jan 15',
      documents: ['Transcripts', 'Recommendation Letters', 'Essays'],
    },
    visa: {
      type: 'Student Visa (UK)',
      steps: [
        'Apply for CAS from Edinburgh',
        'Complete UK visa application',
        'Schedule and attend visa interview',
      ],
      fee: '£348',
    },
    scholarships: [
      {
        name: 'Edinburgh Global Research Scholarship',
        description: 'Partial tuition for international PhD students',
        eligibility: 'International PhD students',
        link: 'https://www.ed.ac.uk/student-funding/postgraduate/international/global/research',
      },
      {
        name: 'Chevening Scholarship',
        description: 'UK government scholarship for international students',
        eligibility: 'Leadership, academic merit',
        link: 'https://www.chevening.org/',
      },
    ],
  },
];
